#!/bin/sh

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

cd /etc/dcompose

case "$1" in
    list)
    for f in available/docker-compose.*.yml; do
      name=$(basename $f)
      printf "$name -> "
      if [ -f "enabled/$name" ]; then
        printf "${GREEN}enabled${NC}\n"
      else
        printf "${RED}disabled${NC}\n"
      fi
    done
    exit 0
    ;;
    enable)
    sudo rm "enabled/docker-compose.yml" 2> /dev/null
    sudo rm "enabled/docker-compose.$2.yml" 2> /dev/null
    sudo test -f "available/docker-compose.yml" && sudo ln -s "../available/docker-compose.yml" "enabled/docker-compose.yml"
    sudo test -f "available/docker-compose.$2.yml" && sudo ln -s "../available/docker-compose.$2.yml" "enabled/docker-compose.$2.yml"
    exit 0
    ;;
    disable)
    sudo rm "enabled/docker-compose.$2.yml" 2> /dev/null
    exit 0
    ;;
esac

sudo docker-compose -p dcompose -f enabled/docker-compose.yml $(find enabled/docker-compose.*.yml | sed -e 's/^/-f /') "$@"
