#!/bin/sh

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

cd /etc/dcompose

case "$1" in
    list)
    for f in available/docker-compose.*.yml; do
      name=$(basename $f)
      if [ -f "enabled/$name" ]; then
        printf "${GREEN}[ enabled]${NC} $name\n"
      else
        printf "${RED}[disabled]${NC} $name\n"
      fi
    done
    exit 0
    ;;
    enable)
    sudo test ! -f "enabled/docker-compose.yml" && test -f "available/docker-compose.yml" && sudo ln -s "../available/docker-compose.yml" "enabled/docker-compose.yml"
    sudo test ! -f "enabled/docker-compose.$2.yml" && sudo test -f "available/docker-compose.$2.yml" && sudo ln -s "../available/docker-compose.$2.yml" "enabled/docker-compose.$2.yml"
    enabled=$?
    if [ -f "on_enable" ] && [ $enabled -eq 0 ]; then
       sudo ./on_enable $2
    fi
    exit 0
    ;;
    disable)
    sudo test -f "enabled/docker-compose.$2.yml"  && sudo rm "enabled/docker-compose.$2.yml" 2> /dev/null
    disabled=$?
    if [ -f "on_disable" ] && [ $disabled -eq 0 ]; then
       sudo ./on_disable $2
    fi
    exit 0
    ;;
esac

sudo docker-compose -p dcompose -f enabled/docker-compose.yml $(find enabled/docker-compose.*.yml | sed -e 's/^/-f /') "$@"
